# Copyright (c) 2024 Ying Wang, Min Li
# SPDX-License-Identifier: GPL-3.0-or-later
r"""
Precomputed symbolic formulas for local polynomial regression.

Port from fastLPR/utility/core/estimated_lwp_estimator.m.

These formulas were derived using symbolic math and provide VECTORIZED
computation of regression estimates. They operate on entire grids at once,
which is much faster than point-by-point numerical solvers.

The formulas compute m = e1' * (S \ T) where:
- S is the design matrix (symmetric, stored as lower triangular)
- T is the weighted response vector
- e1 = [1, 0, 0, ...]' selects the constant term

Author: Ying Wang, Min Li
Translated to Python: 2025
"""

from __future__ import annotations

from typing import Optional, Callable, List, Tuple
import numpy as np


def _prepare_broadcasting(
    s: List[np.ndarray], t: List[np.ndarray]
) -> Tuple[List[np.ndarray], List[np.ndarray]]:
    """
    Prepare s and t arrays for broadcasting.

    If t has more dimensions than s (e.g., multiple responses), add trailing
    dimensions to s to enable proper broadcasting.

    Parameters
    ----------
    s : list of ndarrays
        Design matrix elements
    t : list of ndarrays
        Weighted response elements

    Returns
    -------
    s_broadcast : list of ndarrays
        Design matrix elements with added dimensions for broadcasting
    t_squeezed : list of ndarrays
        Squeezed weighted response elements
    """
    # Squeeze all arrays
    s_squeezed = [np.squeeze(si) for si in s]
    t_squeezed = [np.squeeze(ti) for ti in t]

    # Check if we need to add dimensions to s for broadcasting
    if len(t_squeezed) > 0 and len(s_squeezed) > 0:
        t_ndim = t_squeezed[0].ndim
        s_ndim = s_squeezed[0].ndim

        if t_ndim > s_ndim:
            # Add trailing dimensions to all s elements
            num_dims_to_add = t_ndim - s_ndim
            s_broadcast = []
            for si in s_squeezed:
                si_broadcast = si
                for _ in range(num_dims_to_add):
                    si_broadcast = si_broadcast[..., np.newaxis]
                s_broadcast.append(si_broadcast)
            return s_broadcast, t_squeezed

    return s_squeezed, t_squeezed


def get_lwp_formula(
    dims: int, order: int, is_complex: bool = False
) -> Optional[Callable]:
    r"""
    Get precomputed symbolic formula for local polynomial regression.

    Parameters
    ----------
    dims : int
        Number of predictor dimensions
    order : int
        Polynomial order (0, 1, or 2)
    is_complex : bool, default=False
        Whether data is complex-valued

    Returns
    -------
    mfun : callable or None
        Function that computes m = e1' * (S \ T) given S and T
        Returns None if no precomputed formula is available

    Notes
    -----
    The function signature is: mfun(s, t) where:
    - s : list of ndarrays, lower triangular elements of design matrix S
    - t : list of ndarrays, weighted response vector T
    - Returns: ndarray, regression estimate at each grid point

    Supported cases:
    - 1D, order 1, real: Precomputed formula available
    - 1D, order 2, real: Precomputed formula available
    - 2D, order 1, real: Precomputed formula available
    - 3D, order 1, real: Precomputed formula available
    - 2D, order 2, real: Precomputed formula available (very long!)
    - Other cases: Return None (will use numerical solver)
    """
    if is_complex:
        # No precomputed formulas for complex data yet
        return None

    if dims == 1 and order == 1:
        # 1D local linear regression
        return _lwp_1d_order1_real
    elif dims == 1 and order == 2:
        # 1D local quadratic regression
        return _lwp_1d_order2_real
    elif dims == 2 and order == 1:
        # 2D local linear regression
        return _lwp_2d_order1_real
    elif dims == 3 and order == 1:
        # 3D local linear regression
        return _lwp_3d_order1_real
    elif dims == 2 and order == 2:
        # 2D local quadratic regression
        return _lwp_2d_order2_real
    else:
        # No precomputed formula available
        return None


def _lwp_1d_order1_real(s: List[np.ndarray], t: List[np.ndarray]) -> np.ndarray:
    r"""
    Precomputed formula for 1D local linear regression (order 1).

    This is a direct translation of the MATLAB symbolic formula generated by
    get_lwp_estimator.m for 1D order 1.

    For 1D order 1, we have:
    - nt = 2 (1 + 1 dimension)
    - ns = 3 (2*3/2 lower triangular elements)

    Design matrix S (2x2 symmetric):
    S = [s1  s2]
        [s2  s3]

    Weighted response T (2x1):
    T = [t1, t2]'

    Returns m = e1' * (S \ T) = first element of (S \ T)

    Formula:
    m = (s3*t1 - s2*t2) / (s1*s3 - s2^2)

    Parameters
    ----------
    s : list of ndarrays
        Lower triangular elements of design matrix S
        s[0] = s1, s[1] = s2, s[2] = s3
    t : list of ndarrays
        Weighted response vector T
        t[0] = t1, t[1] = t2

    Returns
    -------
    m : ndarray
        Regression estimate at each grid point
    """
    # Prepare arrays for broadcasting (handles multiple responses)
    s_broadcast, t_squeezed = _prepare_broadcasting(s, t)
    s1, s2, s3 = s_broadcast
    t1, t2 = t_squeezed

    # Numerator (direct translation from MATLAB symbolic formula)
    num = s3 * t1 - s2 * t2

    # Denominator (direct translation from MATLAB symbolic formula)
    den = s1 * s3 - s2**2

    # Direct division to match MATLAB behavior
    # Regularization in solve_regression_system already prevents singular matrices
    result = num / den

    return result


def _lwp_1d_order2_real(s: List[np.ndarray], t: List[np.ndarray]) -> np.ndarray:
    r"""
    Precomputed formula for 1D local quadratic regression (order 2).

    This is a direct translation of the MATLAB symbolic formula generated by
    get_lwp_estimator.m for 1D order 2.

    For 1D order 2, we have:
    - nt = 3 (1 + 1 dimension + 1 quadratic term)
    - ns = 6 (3*4/2 lower triangular elements)

    Design matrix S (3x3 symmetric):
    S = [s1  s2  s4]
        [s2  s3  s5]
        [s4  s5  s6]

    Weighted response T (3x1):
    T = [t1, t2, t3]'

    Returns m = e1' * (S \ T) = first element of (S \ T)

    Formula:
    m = (s5^2*t1 - s2*s5*t3 + s2*s6*t2 + s3*s4*t3 - s3*s5*t2 - s4*s6*t1) /
        (s6*s2^2 - 2*s2*s3*s5 + s4*s3^2 + s1*s5^2 - s1*s4*s6)

    Parameters
    ----------
    s : list of ndarrays
        Lower triangular elements of design matrix S
        s[0] = s1, s[1] = s2, s[2] = s3, s[3] = s4, s[4] = s5, s[5] = s6
    t : list of ndarrays
        Weighted response vector T
        t[0] = t1, t[1] = t2, t[2] = t3

    Returns
    -------
    m : ndarray
        Regression estimate at each grid point
    """
    # Prepare arrays for broadcasting (handles multiple responses)
    s_broadcast, t_squeezed = _prepare_broadcasting(s, t)
    s1, s2, s3, s4, s5, s6 = s_broadcast
    t1, t2, t3 = t_squeezed

    # Numerator (direct translation from MATLAB symbolic formula)
    num = (
        s5**2 * t1
        - s2 * s5 * t3
        + s2 * s6 * t2
        + s3 * s4 * t3
        - s3 * s5 * t2
        - s4 * s6 * t1
    )

    # Denominator (direct translation from MATLAB symbolic formula)
    den = s6 * s2**2 - 2 * s2 * s3 * s5 + s4 * s3**2 + s1 * s5**2 - s1 * s4 * s6

    # Direct division to match MATLAB behavior
    # Regularization in solve_regression_system already prevents singular matrices
    result = num / den

    return result


def _lwp_2d_order1_real(s: List[np.ndarray], t: List[np.ndarray]) -> np.ndarray:
    r"""
    Precomputed formula for 2D local linear regression (order 1).

    This is a direct translation of the MATLAB symbolic formula generated by
    get_lwp_estimator.m for 2D order 1.

    For 2D order 1, we have:
    - nt = 3 (1 + 2 dimensions)
    - ns = 6 (3*4/2 lower triangular elements)

    Design matrix S (3x3 symmetric):
    S = [s1  s2  s3]
        [s2  s4  s5]
        [s3  s5  s6]

    Weighted response T (3x1):
    T = [t1, t2, t3]'

    Returns m = e1' * (S \ T) = first element of (S \ T)

    Formula:
    m = (s5^2*t1 - s2*s5*t3 + s2*s6*t2 + s3*s4*t3 - s3*s5*t2 - s4*s6*t1) /
        (s1*s5^2 + s3^2*s4 + s2^2*s6 - 2*s2*s3*s5 - s1*s4*s6)
    """
    # Prepare arrays for broadcasting (handles multiple responses)
    s_broadcast, t_squeezed = _prepare_broadcasting(s, t)
    s1, s2, s3, s4, s5, s6 = s_broadcast
    t1, t2, t3 = t_squeezed

    # Numerator (direct translation from MATLAB symbolic formula)
    num = (
        s5**2 * t1
        - s2 * s5 * t3
        + s2 * s6 * t2
        + s3 * s4 * t3
        - s3 * s5 * t2
        - s4 * s6 * t1
    )

    # Denominator (direct translation from MATLAB symbolic formula)
    den = s1 * s5**2 + s3**2 * s4 + s2**2 * s6 - 2 * s2 * s3 * s5 - s1 * s4 * s6

    # Direct division to match MATLAB behavior
    # Regularization in solve_regression_system already prevents singular matrices
    result = num / den

    return result


def _lwp_3d_order1_real(s: List[np.ndarray], t: List[np.ndarray]) -> np.ndarray:
    r"""
    Precomputed formula for 3D local linear regression (order 1).

    Port from estimated_lwp_estimator.m.

    For 3D order 1, we have:
    - nt = 4 (1 + 3 dimensions)
    - ns = 10 (4*5/2 lower triangular elements)

    Design matrix S (4x4 symmetric):
    S = [s1  s2  s3  s4 ]
        [s2  s5  s6  s7 ]
        [s3  s6  s8  s9 ]
        [s4  s7  s9  s10]

    Weighted response T (4x1):
    T = [t1, t2, t3, t4]'

    Returns m = e1' * (S \ T) = first element of (S \ T)
    """
    # Prepare arrays for broadcasting (handles multiple responses)
    s_broadcast, t_squeezed = _prepare_broadcasting(s, t)
    s1, s2, s3, s4, s5, s6, s7, s8, s9, s10 = s_broadcast
    t1, t2, t3, t4 = t_squeezed

    # Numerator (direct translation from MATLAB)
    num = (
        -s2 * s9**2 * t2
        - s3 * s7**2 * t3
        - s4 * s6**2 * t4
        + s5 * s9**2 * t1
        + s7**2 * s8 * t1
        + s6**2 * s10 * t1
        + s3 * s6 * s7 * t4
        + s4 * s6 * s7 * t3
        + s2 * s6 * s9 * t4
        - s2 * s6 * s10 * t3
        - s2 * s7 * s8 * t4
        + s2 * s7 * s9 * t3
        - s3 * s5 * s9 * t4
        + s3 * s5 * s10 * t3
        - s3 * s6 * s10 * t2
        + s3 * s7 * s9 * t2
        + s4 * s5 * s8 * t4
        - s4 * s5 * s9 * t3
        + s4 * s6 * s9 * t2
        - s4 * s7 * s8 * t2
        + s2 * s8 * s10 * t2
        - 2 * s6 * s7 * s9 * t1
        - s5 * s8 * s10 * t1
    )

    # Denominator (direct translation from MATLAB)
    den = (
        -(s3**2) * s7**2
        - s4**2 * s6**2
        - s2**2 * s9**2
        + s1 * s5 * s9**2
        + s1 * s7**2 * s8
        + s1 * s6**2 * s10
        + s4**2 * s5 * s8
        + s3**2 * s5 * s10
        + s2**2 * s8 * s10
        + 2 * s3 * s4 * s6 * s7
        - 2 * s2 * s3 * s6 * s10
        + 2 * s2 * s3 * s7 * s9
        + 2 * s2 * s4 * s6 * s9
        - 2 * s2 * s4 * s7 * s8
        - 2 * s3 * s4 * s5 * s9
        - 2 * s1 * s6 * s7 * s9
        - s1 * s5 * s8 * s10
    )

    # Direct division to match MATLAB behavior
    # Regularization in solve_regression_system already prevents singular matrices
    result = num / den

    return result


def _lwp_2d_order2_real(s: List[np.ndarray], t: List[np.ndarray]) -> np.ndarray:
    """
    Precomputed formula for 2D local quadratic regression (order 2).

    Port from estimated_lwp_estimator.m.

    For 2D order 2, we have:
    - nt = 6 (1 + 2 + 3 polynomial terms)
    - ns = 21 (6*7/2 lower triangular elements)

    WARNING: This formula is EXTREMELY long (thousands of terms)!
    It was generated by symbolic math and provides exact vectorized computation.

    NOTE: Currently requires external formula file (../../backup/dev/2d_order2_formula_python.txt)
    which is not included in the package. If this file is missing, the function will
    raise FileNotFoundError. This does not affect any of the JSS paper examples,
    which use 1D order-2 or 2D order-0/1 only. Users requiring 2D order-2 regression
    should contact the package maintainers or use the numerical solver fallback.
    """
    # Prepare arrays for broadcasting (handles multiple responses)
    s_broadcast, t_squeezed = _prepare_broadcasting(s, t)
    (
        s1,
        s2,
        s3,
        s4,
        s5,
        s6,
        s7,
        s8,
        s9,
        s10,
        s11,
        s12,
        s13,
        s14,
        s15,
        s16,
        s17,
        s18,
        s19,
        s20,
        s21,
    ) = s_broadcast
    t1, t2, t3, t4, t5, t6 = t_squeezed

    # This is the MASSIVE formula from MATLAB estimated_lwp_estimator.m
    # It has been automatically converted from MATLAB to Python
    # The formula is extremely long (49,947 characters) but provides exact vectorized computation

    # Read the formula from the data directory inside the package
    import os

    formula_file = os.path.join(
        os.path.dirname(__file__), "data", "2d_order2_formula_python.txt"
    )

    if not os.path.exists(formula_file):
        raise FileNotFoundError(
            f"2D order-2 formula file not found: {formula_file}. "
            "Reinstall the package or use order=0/1 for 2D data."
        )

    with open(formula_file, "r") as f:
        formula_str = f.read().strip()

    # Evaluate the formula
    # The formula is in the form: (numerator) / (denominator)
    return eval(formula_str)
