% GENERATE_LWP_FORMULAS - Generate and save pre-computed LWP estimator formulas
% Copyright (c) 2024-2025 Ying Wang, Min Li
% SPDX-License-Identifier: GPL-3.0-or-later
%
%
% This script generates symbolic formulas for local weighted polynomial (LWP)
% estimators and saves them to estimated_lwp_estimator.m for fast lookup.
%
% The symbolic computation is very slow for high-dimensional cases, so we
% pre-compute the formulas once and store them.
%
% Cases to generate:
%   - 1D: p=0,1,2
%   - 2D: p=0,1,2 (p=2 already exists)
%   - 3D: p=0,1,2
%
% Author: Ying Wang, Min Li
% Date: 2025-10-22

% Resolve paths relative to this script's location (utility/core/)
script_dir = fileparts(mfilename('fullpath'));
utility_dir = fileparts(script_dir);  % utility/
addpath(genpath(utility_dir));

% Cases to generate
cases = {
    % [dx, p, iscomplex, description]
    [1, 0, 0, '1D Order 0 (Nadaraya-Watson)'];
    [1, 1, 0, '1D Order 1 (Local Linear)'];
    [1, 2, 0, '1D Order 2 (Local Quadratic)'];
    [2, 0, 0, '2D Order 0 (Nadaraya-Watson)'];
    [2, 1, 0, '2D Order 1 (Local Linear)'];
    % [2, 2, 0, '2D Order 2 (Local Quadratic)'];  % Already exists
    [3, 0, 0, '3D Order 0 (Nadaraya-Watson)'];
    [3, 1, 0, '3D Order 1 (Local Linear)'];
    [3, 2, 0, '3D Order 2 (Local Quadratic)'];  % This is the slow one!
};

fprintf('Generating LWP estimator formulas...\n\n');

formulas = cell(length(cases), 1);

for i = 1:length(cases)
    dx = cases{i}(1);
    p = cases{i}(2);
    iscomplex = cases{i}(3);
    desc = cases{i}{4};
    
    fprintf('Case %d/%d: %s\n', i, length(cases), desc);
    fprintf('  dx=%d, p=%d, iscomplex=%d\n', dx, p, iscomplex);
    
    tic;
    [~, ~, mfun, ns, nt] = get_lwp_estimator(dx, p, iscomplex);
    t = toc;
    
    fprintf('  Generated in %.2f seconds\n', t);
    fprintf('  ns=%d, nt=%d\n', ns, nt);
    
    % Store the formula
    formulas{i} = struct(...
        'dx', dx, ...
        'p', p, ...
        'iscomplex', iscomplex, ...
        'mfun', mfun, ...
        'ns', ns, ...
        'nt', nt, ...
        'func_str', func2str(mfun));
    
    fprintf('\n');
end

fprintf('All formulas generated!\n\n');

% Now write them to estimated_lwp_estimator.m
fprintf('Writing to estimated_lwp_estimator.m...\n');

output_file = fullfile(script_dir, 'estimated_lwp_estimator.m');
fid = fopen(output_file, 'w');

% Write header
fprintf(fid, 'function [mfun]=estimated_lwp_estimator(dx,p,iscomplex)\n');
fprintf(fid, '%% ESTIMATED_LWP_ESTIMATOR - Pre-computed LWP estimator formulas\n');
fprintf(fid, '%%\n');
fprintf(fid, '%% Returns pre-computed symbolic formulas for local weighted polynomial\n');
fprintf(fid, '%% estimators to avoid slow symbolic computation at runtime.\n');
fprintf(fid, '%%\n');
fprintf(fid, '%% Generated by: generate_lwp_formulas.m\n');
fprintf(fid, '%% Date: %s\n', datestr(now));
fprintf(fid, '%%\n');
fprintf(fid, '%% Author: Ying Wang, Min Li\n');
fprintf(fid, '\n');
fprintf(fid, 'mfun=[];\n\n');

% Write each case
for i = 1:length(formulas)
    f = formulas{i};
    fprintf(fid, '%% Case: dx=%d, p=%d, iscomplex=%d\n', f.dx, f.p, f.iscomplex);
    fprintf(fid, 'if dx==%d && p==%d && ~iscomplex\n', f.dx, f.p);
    fprintf(fid, '    mfun=%s;\n', f.func_str);
    fprintf(fid, 'end\n\n');
end

fprintf(fid, 'end\n');
fclose(fid);

fprintf('Done! File written to: %s\n', output_file);
