#!/usr/bin/env Rscript
# =============================================================================
# STANDARDIZED R vs MATLAB CROSS-VALIDATION TEST
# =============================================================================
# This script reads standardized MATLAB reference data (from refs/*.mat files)
# and compares R implementation results.
#
# Report Format:
# | Test | N | dx | order | Type | MATLAB Time | R Time | Ratio |
# | GCV MaxErr | GCV MSE | BW MaxErr | BW MSE | Mean MaxErr | Mean MSE |
# | Var MaxErr | Var MSE | Status |
#
# Reference files generated by: fastLPR/tests/generate_refs.m
# Reference files location: fastLPR/tests/refs/
#
# Usage:
#   cd fastLPR_R
#   Rscript tests/verify_r.R
#
# Prerequisites:
#   Run MATLAB script first: cd fastLPR && matlab -batch "run('tests/generate_refs.m')"
# =============================================================================

cat("================================================================================\n")
cat("   STANDARDIZED R vs MATLAB CROSS-VALIDATION TEST\n")
cat("================================================================================\n\n")

# Get script directory and set working directory
args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("--file=", "", args[grep("--file=", args)])
if (length(script_path) > 0) {
  script_dir <- normalizePath(dirname(script_path))
  package_root <- dirname(script_dir)  # fastLPR_R/
  repo_root <- dirname(package_root)   # jss-code/
} else {
  # Fallback: assume running from fastLPR_R directory
  package_root <- getwd()
  repo_root <- dirname(package_root)
}
setwd(package_root)

# Setup - source R files from package
suppressWarnings(suppressMessages({
  r_files <- list.files("R", pattern = "\\.R$", full.names = TRUE)
  for (f in r_files) source(f)
  library(R.matlab)
  
  # Compile and load Rcpp with OpenMP if available
  rcpp_loaded <- FALSE
  if (requireNamespace("Rcpp", quietly = TRUE) && 
      requireNamespace("RcppArmadillo", quietly = TRUE) &&
      file.exists("src/fastlpr_rcpp.cpp")) {
    tryCatch({
      library(Rcpp)
      library(RcppArmadillo)
      Rcpp::sourceCpp("src/fastlpr_rcpp.cpp", verbose = FALSE)
      info <- rcpp_info()
      cat(sprintf("Rcpp v%s with OpenMP (%d threads): ENABLED\n", 
                  info$version, info$num_threads))
      rcpp_loaded <- TRUE
    }, error = function(e) {
      cat("Rcpp: DISABLED (compilation failed)\n")
    })
  } else {
    cat("Rcpp: DISABLED (dependencies not found)\n")
  }
}))

# Reference data directory - MATLAB generates refs in fastLPR/tests/refs/
ref_dir <- file.path(repo_root, "fastLPR", "tests", "refs")
cat(sprintf("Reference directory: %s\n", ref_dir))

# Results storage
results <- list()

# Helper function to compute error metrics
compute_errors <- function(r_val, m_val) {
  if (is.null(r_val) || is.null(m_val)) {
    return(list(max_err = NA, mse = NA, max_rel_err = NA))
  }
  r_val <- as.vector(r_val)
  m_val <- as.vector(m_val)
  if (length(r_val) != length(m_val)) {
    min_len <- min(length(r_val), length(m_val))
    r_val <- r_val[1:min_len]
    m_val <- m_val[1:min_len]
  }
  if (any(is.na(r_val)) || any(is.na(m_val))) {
    return(list(max_err = NA, mse = NA, max_rel_err = NA))
  }
  diff <- r_val - m_val
  # Use Mod() for complex numbers to ensure real-valued MSE
  abs_err <- max(Mod(diff), na.rm = TRUE)
  mse_val <- mean(Mod(diff)^2, na.rm = TRUE)
  
  # Compute relative error (use mean of absolute values as scale)
  scale <- mean(abs(m_val))
  if (scale < 1e-10) scale <- 1.0
  rel_err <- abs_err / scale
  
  list(
    max_err = abs_err,
    mse = mse_val,
    max_rel_err = rel_err
  )
}

# Helper to safely extract value
safe_extract <- function(mat, field) {
  if (!is.null(mat[[field]])) {
    return(as.vector(mat[[field]]))
  }
  # Try with dots replaced by underscores
  field_alt <- gsub("_", ".", field)
  if (!is.null(mat[[field_alt]])) {
    return(as.vector(mat[[field_alt]]))
  }
  return(NULL)
}

# Helper to run a test
run_test <- function(test_name, mat_file, dx, order, type, run_func) {
  cat(sprintf("\n>>> %s <<<\n", test_name))
  cat("------------------------------------------------------------\n")

  result <- tryCatch({
    mat_path <- file.path(ref_dir, mat_file)
    if (!file.exists(mat_path)) {
      cat(sprintf("  SKIP: File not found: %s\n", mat_path))
      cat("  Run MATLAB script first: verification/generate_cross_validation_refs.m\n")
      return(list(
        test = test_name, n = NA, dx = dx, order = order, type = type,
        matlab_time = NA, r_time = NA, ratio = NA,
        gcv_max = NA, gcv_mse = NA, bw_max = NA, bw_mse = NA,
        mean_max = NA, mean_mse = NA, var_max = NA, var_mse = NA,
        status = "SKIP"
      ))
    }

    mat <- readMat(mat_path)

    # Extract MATLAB timing
    matlab_time <- if (!is.null(mat$elapsed)) as.numeric(mat$elapsed) else NA

    # Run R implementation with timing
    tic <- Sys.time()
    r_result <- run_func(mat)
    r_time <- as.numeric(difftime(Sys.time(), tic, units = "secs"))

    # Compute ratio
    ratio <- if (!is.na(matlab_time) && matlab_time > 0) r_time / matlab_time else NA

    n <- r_result$n

    # Compute error metrics
    gcv_err <- compute_errors(r_result$gcv_r, r_result$gcv_m)
    bw_err <- compute_errors(r_result$bw_r, r_result$bw_m)
    mean_err <- compute_errors(r_result$mean_r, r_result$mean_m)
    var_err <- compute_errors(r_result$var_r, r_result$var_m)

    # ==========================================================================
    # PASS/FAIL CRITERIA - ALL METRICS MUST PASS (REQ-5)
    # ==========================================================================
    # NO EXCEPTIONS! All metrics use ABSOLUTE error thresholds.
    # Do NOT change these criteria to hide failures - fix the root cause!
    #
    # KDE (order=0): LCV MaxErr < 0.1 + BW MaxErr < threshold
    # Regression (order>0): GCV + BW + Mean (+ Var for hetero)
    is_kde <- (order == 0)

    # Check index difference (id_err) - MATLAB id1se vs R id1se
    r_id <- r_result$id_r
    m_id <- r_result$id_m
    id_err <- if (!is.null(r_id) && !is.null(m_id)) abs(r_id - m_id) else NA

    # ==========================================================================
    # STRICT THRESHOLDS - DO NOT RELAX!
    # ==========================================================================
    # All thresholds must be met for PASS. NO exceptions!

    # BW threshold: Bandwidth selection MUST match
    bw_threshold <- if (dx == 1) 0.02 else 0.05  # STRICT: 2D/3D = 0.05 (was 0.15)

    # GCV threshold: Cross-validation score MUST match
    # Hetero 2D: 0.05 (2D DOF estimation has larger variance due to Hutchinson trace)
    gcv_threshold <- if (type == "mean+var" && dx == 2) 0.05 else 0.01

    # LCV relative threshold for KDE (1% relative error)
    lcv_rel_threshold <- 0.01  # STRICT: 1% relative error for KDE

    # Mean threshold: Prediction accuracy MUST be good
    mean_threshold <- if (dx == 1) 0.05 else 0.1  # STRICT: 2D = 0.1 (was 0.5)

    # Var threshold: Variance estimation (for hetero tests)
    var_threshold <- if (dx == 1) 0.1 else 0.2  # STRICT: Added var check

    # Speed threshold: MUST be < 8x MATLAB (NO exceptions!)
    speed_threshold <- 8.0  # STRICT: Same for all dimensions

    # ==========================================================================
    # PASS/FAIL DETERMINATION - ALL CHECKS MANDATORY
    # ==========================================================================

    # Check each criterion
    bw_pass <- is.na(bw_err$max_err) || bw_err$max_err < bw_threshold
    mean_pass <- is.na(mean_err$max_err) || mean_err$max_err < mean_threshold
    var_pass <- is.na(var_err$max_err) || var_err$max_err < var_threshold
    speed_pass <- is.na(ratio) || ratio < speed_threshold

    # LCV threshold for KDE (ABSOLUTE error per REQ-5)
    lcv_threshold <- 0.1  # STRICT: 0.1 absolute error for KDE LCV
    
    if (is_kde) {
      # KDE: Check LCV + BW (ALL metrics must pass!)
      lcv_pass <- is.na(gcv_err$max_err) || gcv_err$max_err < lcv_threshold
      accuracy_pass <- lcv_pass && bw_pass
    } else {
      # Regression: Check GCV + BW + Mean + Var (if applicable)
      gcv_pass <- is.na(gcv_err$max_err) || gcv_err$max_err < gcv_threshold
      if (type == "mean+var") {
        # Hetero tests: MUST check variance too!
        accuracy_pass <- gcv_pass && bw_pass && mean_pass && var_pass
      } else {
        accuracy_pass <- gcv_pass && bw_pass && mean_pass
      }
    }

    # FINAL STATUS: ALL checks must pass
    status <- if (accuracy_pass && speed_pass) "PASS" else "FAIL"

    # Print which check failed
    if (status == "FAIL") {
      fail_reasons <- c()
      if (!bw_pass) fail_reasons <- c(fail_reasons, sprintf("BW(%.2e>%.2e)", bw_err$max_err, bw_threshold))
      if (is_kde && !lcv_pass) fail_reasons <- c(fail_reasons, sprintf("LCV(%.2e>%.2e)", gcv_err$max_err, lcv_threshold))
      if (!is_kde && !gcv_pass) fail_reasons <- c(fail_reasons, sprintf("GCV(%.2e>%.2e)", gcv_err$max_err, gcv_threshold))
      if (!mean_pass) fail_reasons <- c(fail_reasons, sprintf("Mean(%.2e>%.2e)", mean_err$max_err, mean_threshold))
      if (type == "mean+var" && !var_pass) fail_reasons <- c(fail_reasons, sprintf("Var(%.2e>%.2e)", var_err$max_err, var_threshold))
      if (!speed_pass) fail_reasons <- c(fail_reasons, sprintf("Speed(%.1fx>%.1fx)", ratio, speed_threshold))
      cat(sprintf("  ** FAIL REASON: %s **\n", paste(fail_reasons, collapse = ", ")))
    }

    # Print summary
    cat(sprintf("  n=%d, dx=%d, order=%d, type=%s\n", n, dx, order, type))
    cat(sprintf("  R Time: %.3f sec", r_time))
    if (!is.na(matlab_time)) cat(sprintf(", MATLAB: %.3f sec (ratio: %.2fx)", matlab_time, ratio))
    cat("\n")
    if (is_kde) {
      # For KDE, show relative error (more meaningful for large LCV values)
      cat(sprintf("  LCV MaxErr: %.6e, RelErr: %.2e (<%.2f)\n", gcv_err$max_err, gcv_err$max_rel_err, lcv_rel_threshold))
    } else {
      if (!is.na(gcv_err$max_err)) cat(sprintf("  GCV MaxErr: %.6e, MSE: %.2e\n", gcv_err$max_err, gcv_err$mse))
    }
    if (!is.na(bw_err$max_err)) cat(sprintf("  BW MaxErr: %.6e, MSE: %.2e\n", bw_err$max_err, bw_err$mse))
    if (!is.na(mean_err$max_err)) cat(sprintf("  Mean MaxErr: %.6e, MSE: %.2e\n", mean_err$max_err, mean_err$mse))
    if (!is.na(var_err$max_err)) cat(sprintf("  Var MaxErr: %.6e, MSE: %.2e\n", var_err$max_err, var_err$mse))
    cat(sprintf("  STATUS: %s\n", status))

    list(
      test = test_name, n = n, dx = dx, order = order, type = type,
      matlab_time = matlab_time, r_time = r_time, ratio = ratio,
      gcv_max = gcv_err$max_err, gcv_mse = gcv_err$mse,
      bw_max = bw_err$max_err, bw_mse = bw_err$mse,
      mean_max = mean_err$max_err, mean_mse = mean_err$mse,
      var_max = var_err$max_err, var_mse = var_err$mse,
      status = status
    )
  }, error = function(e) {
    cat(sprintf("  ERROR: %s\n", e$message))
    list(
      test = test_name, n = NA, dx = dx, order = order, type = type,
      matlab_time = NA, r_time = NA, ratio = NA,
      gcv_max = NA, gcv_mse = NA, bw_max = NA, bw_mse = NA,
      mean_max = NA, mean_mse = NA, var_max = NA, var_mse = NA,
      status = "ERROR"
    )
  })

  result
}

# =============================================================================
# TEST 1: 1D KDE (order=0)
# =============================================================================
results[[1]] <- run_test(
  "1D KDE", "ref_1d_kde.mat", dx = 1, order = 0, type = "mean",
  function(mat) {
    x <- matrix(mat$x, ncol = 1)
    hlist <- matrix(as.vector(mat$hlist), ncol = 1)
    opt <- list(order = 0, calc_dof = FALSE)

    res <- cv_fastkde(x, hlist, opt)

    # Evaluate density at data points for comparison
    # R fpp is an interpolator object - use $evaluate method
    fhat_r <- if (!is.null(res$fpp) && !is.null(res$fpp$evaluate)) {
      res$fpp$evaluate(x)
    } else {
      NULL
    }

    list(
      n = nrow(x),
      gcv_r = res$lcv$lcv_m, gcv_m = safe_extract(mat, "lcv_m"),
      bw_r = res$h, bw_m = safe_extract(mat, "h_selected"),
      id_r = res$lcv$id1se, id_m = as.integer(mat$id1se),
      mean_r = fhat_r, mean_m = safe_extract(mat, "fhat_at_x"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 2: 2D KDE (order=0)
# =============================================================================
results[[2]] <- run_test(
  "2D KDE", "ref_2d_kde.mat", dx = 2, order = 0, type = "mean",
  function(mat) {
    x <- mat$x
    hlist <- mat$hlist
    opt <- list(order = 0, calc_dof = FALSE)

    res <- cv_fastkde(x, hlist, opt)

    # Evaluate density at data points for comparison
    # R fpp is an interpolator object - use $evaluate method
    fhat_r <- if (!is.null(res$fpp) && !is.null(res$fpp$evaluate)) {
      res$fpp$evaluate(x)
    } else {
      NULL
    }

    list(
      n = nrow(x),
      gcv_r = res$lcv$lcv_m, gcv_m = safe_extract(mat, "lcv_m"),
      bw_r = res$h, bw_m = safe_extract(mat, "h_selected"),
      id_r = res$lcv$id1se, id_m = as.integer(mat$id1se),
      mean_r = fhat_r, mean_m = safe_extract(mat, "fhat_at_x"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 3: 3D KDE (order=0)
# =============================================================================
results[[3]] <- run_test(
  "3D KDE", "ref_3d_kde.mat", dx = 3, order = 0, type = "mean",
  function(mat) {
    x <- mat$x
    hlist <- mat$hlist
    opt <- list(order = 0, calc_dof = FALSE, flag_power2 = FALSE)

    res <- cv_fastkde(x, hlist, opt)

    # Evaluate density at data points for comparison
    # R fpp is an interpolator object - use $evaluate method
    fhat_r <- if (!is.null(res$fpp) && !is.null(res$fpp$evaluate)) {
      res$fpp$evaluate(x)
    } else {
      NULL
    }

    list(
      n = nrow(x),
      gcv_r = res$lcv$lcv_m, gcv_m = safe_extract(mat, "lcv_m"),
      bw_r = res$h, bw_m = safe_extract(mat, "h_selected"),
      id_r = res$lcv$id1se, id_m = as.integer(mat$id1se),
      mean_r = fhat_r, mean_m = safe_extract(mat, "fhat_at_x"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 4: 1D Local Linear (order=1)
# =============================================================================
results[[4]] <- run_test(
  "1D Order 1", "ref_1d_order1.mat", dx = 1, order = 1, type = "mean",
  function(mat) {
    x <- matrix(mat$x, ncol = 1)
    y <- matrix(mat$y, ncol = 1)
    hlist <- matrix(as.vector(mat$hlist), ncol = 1)

    # FIX 2025-12-01: Use MATLAB random vectors for exact DOF reproducibility
    opt <- list(order = 1, calc_dof = TRUE)
    if (!is.null(mat$dof.random.vectors)) {
      opt$dof_random_vectors <- mat$dof.random.vectors
    }

    res <- cv_fastlpr(x, y, hlist, opt)

    list(
      n = nrow(x),
      gcv_r = res$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res$gcv_yhat$h1se, bw_m = as.numeric(mat$h1se),
      id_r = res$gcv_yhat$id1se, id_m = as.integer(mat$id1se),
      mean_r = as.vector(res$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 5: 2D Local Linear (order=1)
# =============================================================================
results[[5]] <- run_test(
  "2D Order 1", "ref_2d_order1.mat", dx = 2, order = 1, type = "mean",
  function(mat) {
    x <- mat$x
    y <- matrix(mat$y, ncol = 1)
    hlist <- mat$hlist

    # FIX 2025-12-01: Use MATLAB random vectors for exact DOF reproducibility
    opt <- list(order = 1, calc_dof = TRUE)
    if (!is.null(mat$dof.random.vectors)) {
      opt$dof_random_vectors <- mat$dof.random.vectors
    }

    res <- cv_fastlpr(x, y, hlist, opt)

    list(
      n = nrow(x),
      gcv_r = res$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res$gcv_yhat$h1se, bw_m = safe_extract(mat, "h1se"),
      id_r = res$gcv_yhat$id1se, id_m = as.integer(mat$id1se),
      mean_r = as.vector(res$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 6: 1D Local Quadratic (order=2)
# =============================================================================
results[[6]] <- run_test(
  "1D Order 2", "ref_1d_order2.mat", dx = 1, order = 2, type = "mean",
  function(mat) {
    x <- matrix(mat$x, ncol = 1)
    y <- matrix(mat$y, ncol = 1)
    hlist <- matrix(as.vector(mat$hlist), ncol = 1)

    # FIX 2025-12-01: Use MATLAB random vectors for exact DOF reproducibility
    opt <- list(order = 2, calc_dof = TRUE)
    if (!is.null(mat$dof.random.vectors)) {
      opt$dof_random_vectors <- mat$dof.random.vectors
    }

    res <- cv_fastlpr(x, y, hlist, opt)

    list(
      n = nrow(x),
      gcv_r = res$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res$gcv_yhat$h1se, bw_m = as.numeric(mat$h1se),
      id_r = res$gcv_yhat$id1se, id_m = as.integer(mat$id1se),
      mean_r = as.vector(res$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 7: 2D Local Quadratic (order=2)
# =============================================================================
results[[7]] <- run_test(
  "2D Order 2", "ref_2d_order2.mat", dx = 2, order = 2, type = "mean",
  function(mat) {
    x <- mat$x
    y <- matrix(mat$y, ncol = 1)
    hlist <- mat$hlist

    # FIX 2025-12-01: Use MATLAB random vectors for exact DOF reproducibility
    opt <- list(order = 2, calc_dof = TRUE)
    if (!is.null(mat$dof.random.vectors)) {
      opt$dof_random_vectors <- mat$dof.random.vectors
    }

    res <- cv_fastlpr(x, y, hlist, opt)

    list(
      n = nrow(x),
      gcv_r = res$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res$gcv_yhat$h1se, bw_m = safe_extract(mat, "h1se"),
      id_r = res$gcv_yhat$id1se, id_m = as.integer(mat$id1se),
      mean_r = as.vector(res$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 8: Complex Data
# =============================================================================
results[[8]] <- run_test(
  "Complex", "ref_complex.mat", dx = 1, order = 1, type = "mean",
  function(mat) {
    x <- matrix(mat$x, ncol = 1)
    y <- matrix(mat$y, ncol = 1)
    hlist <- matrix(as.vector(mat$hlist), ncol = 1)

    # FIX 2025-12-01: Use MATLAB random vectors for exact DOF reproducibility
    opt <- list(order = 1, calc_dof = TRUE)
    if (!is.null(mat$dof.random.vectors)) {
      opt$dof_random_vectors <- mat$dof.random.vectors
    }

    res <- cv_fastlpr(x, y, hlist, opt)

    list(
      n = nrow(x),
      gcv_r = res$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res$gcv_yhat$h1se, bw_m = as.numeric(mat$h1se),
      id_r = res$gcv_yhat$id1se, id_m = as.integer(mat$id1se),
      mean_r = as.vector(res$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = NULL, var_m = NULL
    )
  }
)

# =============================================================================
# TEST 9: Heteroscedastic 1D (mean + variance estimation)
# Two-step process: 1) estimate mean, 2) estimate variance from residuals^2
# =============================================================================
results[[9]] <- run_test(
  "Hetero 1D", "ref_hetero_1d.mat", dx = 1, order = 1, type = "mean+var",
  function(mat) {
    x <- matrix(mat$x, ncol = 1)
    y <- as.vector(mat$y)
    hlist <- matrix(as.vector(mat$hlist), ncol = 1)

    # Step 1: Estimate mean
    opt_mean <- list(order = 1, calc_dof = TRUE, dstd = 0)
    if (!is.null(mat$dof.random.vectors.mean)) {
      opt_mean$dof_random_vectors <- mat$dof.random.vectors.mean
    }
    res_mean <- cv_fastlpr(x, y, hlist, opt_mean)

    # Step 2: Estimate variance from residuals^2
    residuals <- y - res_mean$yhat
    opt_var <- list(order = 1, calc_dof = TRUE, y_type_out = "variance", dstd = 1)
    if (!is.null(mat$dof.random.vectors.var)) {
      opt_var$dof_random_vectors <- mat$dof.random.vectors.var
    }
    res_var <- cv_fastlpr(x, residuals^2, hlist, opt_var)

    list(
      n = nrow(x),
      gcv_r = res_mean$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res_mean$gcv_yhat$h1se, bw_m = safe_extract(mat, "h1se_mean"),
      id_r = res_mean$gcv_yhat$id1se, id_m = as.integer(mat$id1se.mean),
      mean_r = as.vector(res_mean$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = as.vector(res_var$yhat), var_m = safe_extract(mat, "yhat_var")
    )
  }
)

# =============================================================================
# TEST 10: Heteroscedastic 2D (mean + variance estimation)
# =============================================================================
results[[10]] <- run_test(
  "Hetero 2D", "ref_hetero_2d.mat", dx = 2, order = 1, type = "mean+var",
  function(mat) {
    x <- as.matrix(mat$x)
    y <- as.vector(mat$y)
    hlist <- as.matrix(mat$hlist)

    # Step 1: Estimate mean
    opt_mean <- list(order = 1, calc_dof = TRUE, dstd = 0)
    if (!is.null(mat$dof.random.vectors.mean)) {
      opt_mean$dof_random_vectors <- mat$dof.random.vectors.mean
    }
    res_mean <- cv_fastlpr(x, y, hlist, opt_mean)

    # Step 2: Estimate variance from residuals^2
    residuals <- y - res_mean$yhat
    opt_var <- list(order = 1, calc_dof = TRUE, y_type_out = "variance", dstd = 1)
    if (!is.null(mat$dof.random.vectors.var)) {
      opt_var$dof_random_vectors <- mat$dof.random.vectors.var
    }
    res_var <- cv_fastlpr(x, residuals^2, hlist, opt_var)

    list(
      n = nrow(x),
      gcv_r = res_mean$gcv_yhat$gcv_m, gcv_m = safe_extract(mat, "gcv_m"),
      bw_r = res_mean$gcv_yhat$h1se, bw_m = safe_extract(mat, "h1se_mean"),
      id_r = res_mean$gcv_yhat$id1se, id_m = as.integer(mat$id1se.mean),
      mean_r = as.vector(res_mean$yhat), mean_m = safe_extract(mat, "yhat_mean"),
      var_r = as.vector(res_var$yhat), var_m = safe_extract(mat, "yhat_var")
    )
  }
)

# =============================================================================
# GENERATE REPORT TABLE
# =============================================================================
cat("\n\n")
cat("================================================================================\n")
cat("   CROSS-VALIDATION REPORT TABLE\n")
cat("================================================================================\n\n")

# Header
cat(sprintf("%-12s | %5s | %2s | %5s | %8s | %8s | %8s | %6s | %10s | %10s | %10s | %10s | %10s | %10s | %10s | %10s | %6s\n",
            "Test", "N", "dx", "order", "Type", "MATLAB", "R Time", "Ratio",
            "GCV MaxErr", "GCV MSE", "BW MaxErr", "BW MSE",
            "Mean MaxErr", "Mean MSE", "Var MaxErr", "Var MSE", "Status"))
cat(paste(rep("-", 200), collapse = ""), "\n")

# Data rows
for (res in results) {
  cat(sprintf("%-12s | %5s | %2d | %5d | %8s | %8s | %8.3f | %6s | %10s | %10s | %10s | %10s | %10s | %10s | %10s | %10s | %6s\n",
              res$test,
              ifelse(is.na(res$n), "NA", as.character(res$n)),
              res$dx,
              res$order,
              res$type,
              ifelse(is.na(res$matlab_time), "NA", sprintf("%.3f", res$matlab_time)),
              ifelse(is.na(res$r_time), NA, res$r_time),
              ifelse(is.na(res$ratio), "NA", sprintf("%.2fx", res$ratio)),
              ifelse(is.na(res$gcv_max), "NA", sprintf("%.2e", res$gcv_max)),
              ifelse(is.na(res$gcv_mse), "NA", sprintf("%.2e", res$gcv_mse)),
              ifelse(is.na(res$bw_max), "NA", sprintf("%.2e", res$bw_max)),
              ifelse(is.na(res$bw_mse), "NA", sprintf("%.2e", res$bw_mse)),
              ifelse(is.na(res$mean_max), "NA", sprintf("%.2e", res$mean_max)),
              ifelse(is.na(res$mean_mse), "NA", sprintf("%.2e", res$mean_mse)),
              ifelse(is.na(res$var_max), "NA", sprintf("%.2e", res$var_max)),
              ifelse(is.na(res$var_mse), "NA", sprintf("%.2e", res$var_mse)),
              res$status))
}

cat(paste(rep("-", 200), collapse = ""), "\n")

# Summary
n_pass <- sum(sapply(results, function(r) r$status == "PASS"))
n_fail <- sum(sapply(results, function(r) r$status == "FAIL"))
n_error <- sum(sapply(results, function(r) r$status == "ERROR"))
n_skip <- sum(sapply(results, function(r) r$status == "SKIP"))
total <- length(results)

cat(sprintf("\nSUMMARY: %d PASS, %d FAIL, %d ERROR, %d SKIP (Total: %d)\n",
            n_pass, n_fail, n_error, n_skip, total))

if (n_pass == total) {
  cat("\n*** ALL TESTS PASSED ***\n")
} else if (n_skip > 0) {
  cat("\n*** SOME TESTS SKIPPED - Run MATLAB reference generation first ***\n")
  cat("  matlab -batch \"run('verification/generate_cross_validation_refs.m')\"\n")
} else if (n_fail > 0 || n_error > 0) {
  cat("\n*** SOME TESTS FAILED - INVESTIGATION NEEDED ***\n")
}

# Save results
saveRDS(results, "verification/cross_validation_results_r.rds")
cat("\nResults saved to: verification/cross_validation_results_r.rds\n")

cat("\n================================================================================\n")
cat("Done!\n")

# Return non-zero exit code if any tests failed
if (n_fail > 0 || n_error > 0) {
  quit(status = 1)
}
