# ==============================================================================
# Unit Tests for NUFFT Type-1 Implementation (Python)
# ==============================================================================
#
# Cross-language validation against MATLAB reference data.
# Reference files generated by: fastLPR/tests/generators/generate_nufft_refs.m
# Reference files location: fastLPR/tests/refs/crosslang_unit/
#
# Tests include:
# 1. Cross-language tests (Python vs MATLAB reference)
# 2. Self-consistency tests (no external reference needed)
# 3. Edge case tests (M=1, constant y, boundary x)
# 4. Multi-dimensional tests (1D, 2D, 3D)
# 5. Complex data tests
#
# Author: fastLPR Development Team
# Copyright (c) 2024-2025 fastLPR Development Team
# License: GPL-3.0-or-later
# ==============================================================================

import pytest
import numpy as np
import os
from pathlib import Path
from scipy.io import loadmat

# pytest automatically loads conftest.py
RANDOM_SEED = 42

# Import the module under test
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from fastlpr.nufftn_type1 import nufftn_type1


# =============================================================================
# Helper Functions
# =============================================================================

def get_ref_path(filename):
    """Get path to MATLAB reference file."""
    test_dir = Path(__file__).parent
    ref_dir = test_dir.parent.parent / "fastLPR" / "tests" / "refs" / "crosslang_unit"
    return ref_dir / filename


def load_nufft_ref(filename):
    """Load MATLAB reference data for NUFFT tests."""
    ref_path = get_ref_path(filename)
    if not ref_path.exists():
        pytest.skip(f"Reference file not found: {ref_path}")

    mat = loadmat(str(ref_path), squeeze_me=True, struct_as_record=False)
    return mat


def compute_naive_dft_1d(x, y, N):
    """Compute naive DFT for 1D as reference.

    Formula: (1/M) * sum(y * exp(-i*2*pi*k*x))
    Matches NUFFT(isdeconv=False) with ~0.12 error (spreading approximation).
    """
    M = len(x)
    x_flat = np.ravel(x)
    y_flat = np.ravel(y)
    k = np.arange(-N//2, N - N//2)
    naive = np.zeros(N, dtype=complex)
    for ik, kval in enumerate(k):
        phase = -2 * np.pi * kval * x_flat
        naive[ik] = np.sum(y_flat * np.exp(1j * phase)) / M
    return naive


def compare_results(py_result, ref_result):
    """Compute comparison metrics between Python and reference results."""
    py_vec = np.ravel(py_result)
    ref_vec = np.ravel(ref_result)

    # Handle complex arrays
    if np.iscomplexobj(py_vec) or np.iscomplexobj(ref_vec):
        py_vec = np.asarray(py_vec, dtype=complex)
        ref_vec = np.asarray(ref_vec, dtype=complex)

    abs_err = np.abs(py_vec - ref_vec)
    max_abs_err = np.max(abs_err)
    mean_abs_err = np.mean(abs_err)

    # Compute relative error with safe denominator
    denom = np.maximum(np.abs(ref_vec), 1e-10)
    rel_err = abs_err / denom
    significant_mask = np.abs(ref_vec) > 1e-10
    max_rel_err = np.max(rel_err[significant_mask]) if np.any(significant_mask) else 0.0

    return {
        'max_abs_err': float(max_abs_err),
        'mean_abs_err': float(mean_abs_err),
        'max_rel_err': float(max_rel_err)
    }


# =============================================================================
# Section 1: Cross-Language Tests - ARCHIVED
# =============================================================================
# TestNUFFTCrossLanguage class archived - XL tests should only be at E2E level
# See: dev/archive/py-nufft-tests-20260109/archived_nufft_tests.py


# =============================================================================
# Section 2: Self-Consistency Tests
# =============================================================================

class TestNUFFTSelfConsistency:
    """Self-consistency tests that don't need external reference."""

    def test_constant_y_1d(self):
        """UNIT: nufftn_type1 with constant y produces expected spectrum"""
        np.random.seed(RANDOM_SEED)
        M = 100
        N = 32

        x = np.random.rand(M, 1)
        y = np.ones((M, 1)) * 5.0  # Constant value

        # Shift x to [-0.5, 0.5] for proper centering
        x_centered = x - 0.5
        df = np.array([1.0 / N])

        result = nufftn_type1(x_centered, y, df=df, iflag=-1, acc=9, isdeconv=True)

        # For constant y, DC component should dominate
        # Find index of DC component (should be near center after fftshift-like arrangement)
        dc_idx = N // 2
        dc_power = np.abs(result[dc_idx, 0])
        total_power = np.sum(np.abs(result))

        # DC should be significant portion of total power
        assert dc_power > 0.5 * total_power / N, \
            f"DC power {dc_power:.2e} should be significant"

    # test_symmetric_y_1d - ARCHIVED (similar to test_constant_y_1d)
    # test_linearity_1d - ARCHIVED (keep only accuracy test)

    def test_accuracy_improves_with_parameter(self):
        """UNIT: Higher accuracy parameter should not degrade results"""
        np.random.seed(RANDOM_SEED)
        M = 50
        N = 16

        x = np.random.rand(M, 1) - 0.5
        y = np.sin(2 * np.pi * x) + 0.1 * np.random.randn(M, 1)
        df = np.array([1.0 / N])

        # Run with increasing accuracy
        results = {}
        for acc in [4, 6, 9, 12]:
            results[acc] = nufftn_type1(x, y, df=df, iflag=-1, acc=acc, isdeconv=True)

        # Higher accuracy should converge (results should stabilize)
        # Compare acc=9 vs acc=12 - should be very close
        diff_9_12 = compare_results(results[9], results[12])

        # They should be very close (both are high accuracy)
        assert diff_9_12['max_abs_err'] < 1e-6, \
            f"acc=9 vs acc=12 difference={diff_9_12['max_abs_err']:.2e} should be < 1e-6"

    def test_reproducible_results(self):
        """UNIT: nufftn_type1 produces reproducible results"""
        np.random.seed(RANDOM_SEED)
        M = 50
        N = 20

        x = np.random.rand(M, 1)
        y = np.sin(2 * np.pi * x)
        df = np.array([1.0 / N])

        result1 = nufftn_type1(x, y, df=df, iflag=-1, acc=9, isdeconv=True)
        result2 = nufftn_type1(x, y, df=df, iflag=-1, acc=9, isdeconv=True)

        # Same inputs should give identical outputs
        np.testing.assert_array_equal(result1, result2,
            err_msg="Results should be reproducible")


# =============================================================================
# Section 3: Edge Case Tests
# =============================================================================

class TestNUFFTEdgeCases:
    """Edge case tests for robustness."""

    def test_single_point_1d(self):
        """UNIT: nufftn_type1 handles M=1 (single point)"""
        x = np.array([[0.0]])
        y = np.array([[1.0]])
        N = 8
        df = np.array([1.0 / N])

        result = nufftn_type1(x, y, df=df, iflag=-1, acc=6, isdeconv=True)

        # Should return valid result
        assert result.shape[0] == N
        assert not np.any(np.isnan(result))
        assert not np.any(np.isinf(result))

    def test_two_points_1d(self):
        """UNIT: nufftn_type1 handles M=2 (two points)"""
        x = np.array([[0.1], [0.9]])
        y = np.array([[1.0], [2.0]])
        N = 8
        df = np.array([1.0 / N])

        # Shift to center
        x_centered = x - 0.5

        result = nufftn_type1(x_centered, y, df=df, iflag=-1, acc=6, isdeconv=True)

        assert result.shape[0] == N
        assert not np.any(np.isnan(result))
        assert not np.any(np.isinf(result))

    # test_large_n_1d - ARCHIVED: 2026-01-10 (not in R reference)
    # See: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py

    def test_boundary_x_1d(self):
        """UNIT: nufftn_type1 handles x values at boundaries"""
        # x values at exact boundaries [-0.5, 0.5]
        x = np.array([[-0.5], [-0.25], [0.0], [0.25], [0.49999]])
        y = np.array([[1.0], [2.0], [3.0], [2.0], [1.0]])
        N = 8
        df = np.array([1.0 / N])

        result = nufftn_type1(x, y, df=df, iflag=-1, acc=6, isdeconv=True)

        assert result.shape[0] == N
        assert not np.any(np.isnan(result))
        assert not np.any(np.isinf(result))

    # test_zero_y_1d - ARCHIVED (redundant with test_constant_y_1d)


# =============================================================================
# Section 4: Multi-Column Y Tests - ARCHIVED
# =============================================================================
# TestNUFFTMultiColumn class archived - not in R reference (7 tests)
# See: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py


# =============================================================================
# Section 5: 2D and 3D Tests - ARCHIVED
# =============================================================================
# TestNUFFT2D and TestNUFFT3D classes archived - redundant with E2E XL tests
# See: dev/archive/py-nufft-tests-20260109/archived_nufft_tests.py


# =============================================================================
# Section 6: Numerical Stability Tests - ARCHIVED
# =============================================================================
# TestNUFFTNumericalStability class archived - not in R reference (7 tests)
# See: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py


# =============================================================================
# Section 7: iflag Tests - ARCHIVED
# =============================================================================
# TestNUFFTIflag class archived - not in R reference (7 tests)
# See: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py


# =============================================================================
# Section 8: isdeconv Tests
# =============================================================================

class TestNUFFTIsdeconv:
    """Tests for isdeconv parameter."""

    # test_isdeconv_false - ARCHIVED: 2026-01-10 (not in R reference)
    # See: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py

    def test_nufft_vs_naive_dft_1d(self):
        """UNIT: NUFFT(isdeconv=False) matches naive DFT within tolerance.

        Note: Spreading kernel introduces ~0.12 error at acc=12.
        """
        np.random.seed(RANDOM_SEED)
        M = 100
        N = 32

        x = np.random.rand(M, 1) - 0.5  # [-0.5, 0.5]
        y = np.sin(2 * np.pi * x)
        df = np.array([1.0 / N])

        # NUFFT without deconvolution
        result = nufftn_type1(x, y, df=df, iflag=-1, acc=12, isdeconv=False)

        # Naive DFT
        naive = compute_naive_dft_1d(x, y, N)

        # Compare (tolerance 0.15 for spreading approximation)
        max_err = np.max(np.abs(np.ravel(result) - naive))
        assert max_err < 0.15, \
            f"NUFFT vs naive DFT: max_err={max_err:.2e} should be < 0.15"

    # test_isdeconv_difference - ARCHIVED (redundant with test_isdeconv_false)
    # See: dev/archive/py-nufft-tests-20260109/archived_nufft_tests.py


# =============================================================================
# ARCHIVED: 2026-01-10
# Source: fastLPR_py/tests/test_nufft.py
# Archive: dev/archive/tests-archive-20260110/python/unit/archived_test_nufft_extra.py
# Reason: Test unification - not in R reference (7 tests)
# Archived tests (5 total):
# - TestNUFFTEdgeCases.test_large_n_1d
# - TestNUFFTMultiColumn.test_multi_column_y_1d
# - TestNUFFTNumericalStability.test_very_small_y
# - TestNUFFTNumericalStability.test_very_large_y
# - TestNUFFTIflag.test_iflag_positive
# - TestNUFFTIsdeconv.test_isdeconv_false
# =============================================================================
